container:
    image: cirrusci/android-sdk:29
    cpu: 6
    memory: 10G
    kvm: true

ui_tests_api16_task:
    name: UI Tests (Android 4.1.2)
    run_tests_script:
        - ./config/scripts/run_emulator_tests.sh "system-images;android-16;default;x86"

ui_tests_api29_task:
    name: UI Tests (Android 10)
    run_tests_script:
        - ./config/scripts/run_emulator_tests.sh "system-images;android-29;google_apis;x86_64"
