name: CI

on:
    push:
      branches:
        - master
    pull_request:
    schedule:
        -   cron: '30 5 * * *'
    workflow_dispatch:

jobs:
    ci:
        runs-on: macos-14
        steps:
            -   uses: actions/checkout@v4

            -   name: Set up Java 17
                uses: actions/setup-java@v4
                with:
                    distribution: temurin
                    java-version: 17
                    cache: 'gradle'

            -   uses: gradle/wrapper-validation-action@v1

            -   name: Install NDK
                run: |
                    SDKMANAGER=${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager
                    echo "y" | $SDKMANAGER "ndk;23.1.7779620" --sdk_root=${ANDROID_SDK_ROOT}

            -   name: Run Preview build
                run: ./gradlew assemblepreview

            -   name: Upload artifact to GitHub
                uses: actions/upload-artifact@v4
                with:
                    name: RedReader-debug.apk
                    path: ./src/build/outputs/apk/preview/app-preview.apk
