name: Tests

on: [push, pull_request]

jobs:

    unitTest:
        name: Unit tests
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Run unit tests
                run: ./gradlew test
